import {
  activeLayerCount,
  arrangementLayers,
  type ArrangementBar,
} from "../music/model";
import { harmonicFunction } from "../music/harmony";
import { heardPlayback } from "./learningEvidence";
import {
  exerciseContentSchema,
  lessonContentSchema,
  type LessonContext,
  type LessonDefinition,
} from "./types";

function analysed(
  experiments: LessonContext["experiments"],
  sourceId: string,
  minimum: number,
): boolean {
  const values = experiments["source.analysis"]?.values ?? [];
  return new Set(values.filter((value) => value.startsWith(sourceId + ":"))).size >= minimum;
}

function harmonicEdits(experiments: LessonContext["experiments"]): number {
  return Object.entries(experiments).reduce(
    (total, [key, value]) =>
      total + (key.startsWith("harmony.chord.") ? value.changes : 0),
    0,
  );
}

function formEdits(experiments: LessonContext["experiments"]): number {
  return Object.entries(experiments).reduce(
    (total, [key, value]) =>
      total + (key.startsWith("form.") ? value.changes : 0),
    0,
  );
}

function melodyEdits(experiments: LessonContext["experiments"]): number {
  return experiments["melody.edit"]?.changes ?? 0;
}

function differenceCount(left: ArrangementBar, right: ArrangementBar): number {
  return arrangementLayers.filter((layer) => left[layer] !== right[layer]).length;
}

function sharedCount(left: ArrangementBar, right: ArrangementBar): number {
  return arrangementLayers.filter((layer) => left[layer] && right[layer]).length;
}

function soundingCount(sequence: Array<number | null>): number {
  return sequence.filter((note) => note !== null).length;
}

const lesson = lessonContentSchema.parse({
  id: "schoenberg.large-form-functions",
  number: 16,
  title: "Transitions, retransitions & codas",
  eyebrow: "Schoenberg · Large forms",
  hero:
    "Learn the connective and closing functions that let large forms move between stable themes, find their way back, and finish decisively.",
  description:
    "Large forms need more than a sequence of themes. A transition creates directed motion between stable regions, a retransition prepares a return, subordinate material supplies contrast without losing coherence, and a coda completes energy already generated by the movement.",
  overview:
    "Treat these passages by function rather than by length. Ask what must become stable, what must become fluid, what should be liquidated, and what the listener should expect next.",
});

export const schoenbergLargeFormFunctionsLesson: LessonDefinition = {
  ...lesson,
  exercises: [
    {
      ...exerciseContentSchema.parse({
        id: "schoenberg.large-form-functions.a",
        letter: "A",
        title: "Make a transition move",
        learn:
          "A transition is a directed process: establish enough identity to start clearly, create harmonic motion, reduce characteristic detail, and arrive ready for the next stable idea.",
        explanation:
          "A transition is not merely extra music between two themes. Its function is to turn stability into motion. It may grow from the end of the principal theme or begin with a new short idea, but once its identity is established it should become increasingly fluid. Harmonic movement is central because the ear must stop hearing the opening region as settled and begin expecting another stable region.

A useful transition therefore changes its behaviour as it proceeds. Characteristic material can be repeated just enough to become intelligible, then shortened, sequenced or liquidated while the harmony points forward. The end should not sound like another self-contained theme with a full stop. It should create an upbeat condition - a harmony and level of activity that makes the following arrival feel prepared. In this exercise the four harmonic slots are a compact model of that trajectory, not a literal transcription of a larger classical transition.",
        instruction:
          "Study all four transition functions below. In Harmonic Function, build a four-slot route with at least three sounding chords. Start from a tonic-function chord, introduce at least one non-tonic function in the middle, and end on a dominant-function chord rather than resolving it immediately. Change at least three chord slots during this exercise and play the progression after each substantial revision. Listen specifically for the difference between a progression that merely cycles and one whose final harmony makes the next section feel imminent.",
        recognition:
          "Does the final harmony feel like preparation for something that has not arrived yet, while the opening still gave you a clear point of departure?",
        source: {
          reference: "Chapter XVIII - The Transition",
          focus:
            "A transition establishes an idea, moves harmonically, liquidates characteristic detail and prepares the following stable region.",
          exampleIds: ["s16.transition"],
        },
        terms: [
          {
            term: "Transition",
            definition:
              "A connecting formal passage whose changing harmony and thematic treatment move from one stable region toward another.",
          },
          {
            term: "Liquidation",
            definition:
              "Progressive removal of characteristic motive-features until a more neutral residue remains.",
          },
          {
            term: "Upbeat harmony",
            definition:
              "A preparatory harmony whose tension and placement make the following formal arrival feel expected.",
          },
        ],
        workspace: "harmonic-function",
        checksLabel: "Direct the transition",
        successLabel: "The harmony now leaves stability and ends in preparation",
      }),
      evaluate: ({ harmonicProgression, experiments }) => {
        const chords = harmonicProgression.filter((chord) => chord !== null);
        const first = harmonicProgression[0];
        const last = [...harmonicProgression].reverse().find((chord) => chord !== null);
        const functions = chords.map((chord) => harmonicFunction(chord));
        return [
          {
            label: "You studied the four transition functions",
            complete: analysed(experiments, "s16.transition", 4),
          },
          {
            label: "You revised the harmonic route",
            complete: harmonicEdits(experiments) >= 3,
          },
          { label: "You listened to the transition", complete: heardPlayback(experiments) },
          {
            label: "The route begins from tonic stability",
            complete: Boolean(first && harmonicFunction(first) === "tonic"),
          },
          {
            label: "The middle contains harmonic departure",
            complete: functions.some((fn) => fn !== "tonic"),
          },
          {
            label: "The transition ends on dominant preparation",
            complete: Boolean(last && harmonicFunction(last) === "dominant"),
          },
        ];
      },
    },
    {
      ...exerciseContentSchema.parse({
        id: "schoenberg.large-form-functions.b",
        letter: "B",
        title: "Liquidate into a retransition",
        learn:
          "A retransition makes return possible by neutralising the activity of the contrasting region and reducing material until the returning theme can enter clearly.",
        explanation:
          "A retransition is more specific than a generic transition because its destination is already known: the principal material is coming back. The modulatory work may have begun before the retransition itself, so its most audible job can be the progressive removal of obligations created by the preceding music. Motive-forms become shorter or less characteristic, rhythmic activity may simplify, and the harmony can settle into a long preparatory condition.

The important perceptual change is from ongoing argument to expectation. If the passage keeps introducing new characteristic ideas right up to the return, the entrance of the principal theme competes with unresolved material. If everything stops abruptly, the return feels pasted on. Liquidation solves both problems. A residue can still remember the preceding material while no longer demanding continuation. The Motif workspace lets you practise that process directly by thinning a line toward its final block.",
        instruction:
          "Study the retransition analysis, then use the Motif workspace to make the first eight steps materially active and the final four steps noticeably sparser. Keep at least three sounding notes in steps 1-4 so there is a recognisable idea to reduce. By steps 13-16, leave no more than two sounding notes. Make at least five melody edits and play the complete sixteen-step line several times. Do not simply erase the end in one gesture: listen after intermediate versions and aim for a gradual loss of characteristic activity before the imagined return.",
        recognition:
          "Do the last four steps feel like a residue that points toward a return, rather than like a new phrase or an accidental gap?",
        source: {
          reference: "Chapter XVIII - The Retransition",
          focus:
            "Retransition prepares the principal return through remodulation, liquidation and an extended preparatory condition.",
          exampleIds: ["s16.retransition"],
        },
        terms: [
          {
            term: "Retransition",
            definition:
              "A passage whose formal destination is the return of principal material, often combining harmonic preparation with liquidation.",
          },
          {
            term: "Residue",
            definition:
              "The simplified remainder of earlier motive-material after characteristic features have been progressively removed.",
          },
          {
            term: "Preparation",
            definition:
              "Musical activity that makes a coming formal event expected before it actually arrives.",
          },
        ],
        workspace: "motif",
        checksLabel: "Prepare the return",
        successLabel: "The motive now thins into a convincing return preparation",
      }),
      evaluate: ({ melody, experiments }) => [
        {
          label: "You studied how a retransition prepares return",
          complete: analysed(experiments, "s16.retransition", 4),
        },
        {
          label: "You revised the motive substantially",
          complete: melodyEdits(experiments) >= 5,
        },
        { label: "You listened through the liquidation", complete: heardPlayback(experiments) },
        {
          label: "The opening contains material to liquidate",
          complete: soundingCount(melody.slice(0, 4)) >= 3,
        },
        {
          label: "The final block is sparse",
          complete: soundingCount(melody.slice(12, 16)) <= 2,
        },
        {
          label: "Activity decreases toward the end",
          complete:
            soundingCount(melody.slice(0, 8)) >
            soundingCount(melody.slice(8, 16)),
        },
      ],
    },
    {
      ...exerciseContentSchema.parse({
        id: "schoenberg.large-form-functions.c",
        letter: "C",
        title: "Build a subordinate group",
        learn:
          "Subordinate material should provide a stable contrast after the transition, but contrast can come from construction, texture, rhythm and character rather than from an unrelated tune.",
        explanation:
          "The subordinate region has a different function from the transition that leads into it. The transition is fluid; the subordinate group establishes a new stable area. Its material can still derive from the same basic motive, yet it should be differentiated strongly enough that the listener hears a new formal role. Changes of mood, rhythm, register, texture, harmony and motive-form can all contribute to that contrast.

A useful distinction is between thematic contrast and construction. Subordinate material is often looser than a principal theme: repetition, juxtaposition, sequence and several shorter formulations can replace the tightly integrated development of one compact opening idea. This is why a subordinate group does not have to be a single lyrical melody. In the Phrase & Form workspace, treat the first block as principal material and the following contrasting blocks as a compact subordinate group whose changing layer profiles create contrast while retaining at least one common thread.",
        instruction:
          "Study the subordinate-group analysis. In Phrase & Form, set the first block to A and the next two blocks to B and B. Give A at least two active layers. Make the first B differ from A in at least two layer choices while retaining at least one active layer in common. Make the second B related to the first B but not identical by changing at least one layer while preserving at least one. Perform at least four form edits, then play through the first three blocks without stopping and judge whether B sounds stable enough to be a region rather than merely a bridge.",
        recognition:
          "After the moving transition idea, does the B region feel like a new stable thematic area with its own character, while still belonging to the same piece?",
        source: {
          reference: "Chapter XVIII - Group of Subordinate Themes",
          focus:
            "Subordinate material contrasts with the principal theme while often using looser construction, repetition and juxtaposition.",
          exampleIds: ["s16.subordinate-group"],
        },
        terms: [
          {
            term: "Subordinate group",
            definition:
              "One or more contrasting thematic formulations that establish the secondary stable region of a larger form.",
          },
          {
            term: "Loose construction",
            definition:
              "A less tightly integrated formal organization that can rely more on repetition, sequence and juxtaposition.",
          },
          {
            term: "Stable region",
            definition:
              "A passage in which harmony and thematic identity feel established rather than continuously in transit.",
          },
        ],
        workspace: "phrase-form",
        checksLabel: "Establish the subordinate region",
        successLabel: "The subordinate group now contrasts and still feels coherent",
      }),
      evaluate: ({ formSettings, experiments }) => {
        const [a, b1, b2] = formSettings.layers;
        return [
          {
            label: "You studied subordinate-group construction",
            complete: analysed(experiments, "s16.subordinate-group", 4),
          },
          { label: "You edited the macro form", complete: formEdits(experiments) >= 4 },
          { label: "You listened across the formal regions", complete: heardPlayback(experiments) },
          {
            label: "The labels identify principal and subordinate regions",
            complete:
              formSettings.sections[0] === "A" &&
              formSettings.sections[1] === "B" &&
              formSettings.sections[2] === "B",
          },
          {
            label: "The first subordinate block contrasts but stays connected",
            complete:
              activeLayerCount(a) >= 2 &&
              differenceCount(a, b1) >= 2 &&
              sharedCount(a, b1) >= 1,
          },
          {
            label: "The subordinate group develops internally",
            complete:
              differenceCount(b1, b2) >= 1 &&
              sharedCount(b1, b2) >= 1,
          },
        ];
      },
    },
    {
      ...exerciseContentSchema.parse({
        id: "schoenberg.large-form-functions.d",
        letter: "D",
        title: "Close with a coda",
        learn:
          "A coda should confirm and complete the movement after its formal obligations are already resolved, not repair a missing return or introduce another large problem.",
        explanation:
          "A coda is an addition after the main formal course has done its essential work. It can recall earlier material, shorten it, liquidate it further or reinforce tonic closure. What makes it a coda is therefore not a particular length or theme but its position and function: it follows a form that could already close and extends the sense of completion. A coda cannot substitute for a recapitulation that failed to restore the necessary tonal or thematic balance.

Many effective codas reduce rather than expand. Cadential gestures may become shorter, motives can shrink to fragments, and repeated tonic confirmation can replace developmental motion. A large coda can certainly intensify energy, but it should still feel like consequence rather than a new exposition. Here the final block will act as a compressed coda after statement, contrast and return. Keep enough of the returning identity to make the connection audible, but reduce the active layer count so the final block sounds like completion.",
        instruction:
          "Study the coda analysis. In Phrase & Form, set the four blocks to A → B → A′ → A′. Give the returning third block at least two active layers and make it share at least two layers with the opening A. Treat the final block as the coda: keep at least one active layer from the return, but use fewer active layers than the third block. Make at least four form edits and play all four blocks continuously. Compare a fuller final block with the reduced version before deciding which one produces the clearest sense of completion.",
        recognition:
          "Does the last block sound as though the piece is finishing material it already owns, rather than opening another section?",
        source: {
          reference: "Chapter XVIII - The Coda",
          focus:
            "A coda is an optional closing addition that confirms the completed form through recall, reduction, liquidation and cadential reinforcement.",
          exampleIds: ["s16.coda"],
        },
        terms: [
          {
            term: "Coda",
            definition:
              "A closing addition that follows the essential form and strengthens completion without taking over an unresolved structural task.",
          },
          {
            term: "Codetta",
            definition:
              "A short closing formulation, often one of several progressively reduced gestures near an ending.",
          },
          {
            term: "Tonic confirmation",
            definition:
              "Repeated or prolonged emphasis on the home harmony after the main tonal argument has been resolved.",
          },
        ],
        workspace: "phrase-form",
        checksLabel: "Complete the form",
        successLabel: "The coda now confirms the return without starting again",
      }),
      evaluate: ({ formSettings, experiments }) => {
        const [opening, , returning, coda] = formSettings.layers;
        return [
          {
            label: "You studied how a coda completes a form",
            complete: analysed(experiments, "s16.coda", 4),
          },
          { label: "You shaped the ending", complete: formEdits(experiments) >= 4 },
          { label: "You listened through return and coda", complete: heardPlayback(experiments) },
          {
            label: "The macro plan reaches return before the coda",
            complete:
              formSettings.sections[0] === "A" &&
              formSettings.sections[1] === "B" &&
              formSettings.sections[2] === "A′" &&
              formSettings.sections[3] === "A′",
          },
          {
            label: "The return recovers the opening identity",
            complete: sharedCount(opening, returning) >= 2,
          },
          {
            label: "The coda reduces while retaining a connection",
            complete:
              sharedCount(returning, coda) >= 1 &&
              activeLayerCount(coda) >= 1 &&
              activeLayerCount(coda) < activeLayerCount(returning),
          },
        ];
      },
    },
  ],
};
