import {
  sequenceEvents,
  type SourceScoreExample,
} from "./sourceScore";

const examples = {
  "s01-ex2e": {
    id: "s01-ex2e",
    lessonId: "schoenberg.phrase-motive",
    example: "Ex. 2e",
    title: "A complete phrase",
    work: "Beethoven · Symphony No. 3-I",
    printedPage: 5,
    scanPage: 13,
    scope: "melodic transcription",
    scopeNote:
      "Native transcription of the cello theme used by Schoenberg. It reproduces the melodic line relevant to the phrase discussion; the orchestral accompaniment is not part of this excerpt.",
    key: "E♭ major",
    meter: "3/4",
    tempo: "Allegro con brio",
    bpm: 116,
    totalUnits: 60,
    events: sequenceEvents("s01-ex2e", [
      { start: 0, duration: 8, pitch: "Eb3", staff: "bass" },
      { start: 8, duration: 4, pitch: "G3", staff: "bass" },
      { start: 12, duration: 8, pitch: "Eb3", staff: "bass" },
      { start: 20, duration: 4, pitch: "Bb2", staff: "bass" },
      { start: 24, duration: 4, pitch: "Eb3", staff: "bass" },
      { start: 28, duration: 4, pitch: "G3", staff: "bass" },
      { start: 32, duration: 4, pitch: "Bb3", staff: "bass" },
      { start: 36, duration: 8, pitch: "Eb3", staff: "bass" },
      { start: 44, duration: 4, pitch: "D3", staff: "bass" },
      { start: 48, duration: 12, pitch: "C#3", staff: "bass" },
    ]),
    segments: [
      {
        id: "phrase",
        label: "phrase",
        description:
          "Follow the whole span as one breath-like structural unit rather than treating each bar as a separate idea.",
        start: 0,
        end: 60,
        staff: "bass",
      },
    ],
  },
  "s01-ex4c": {
    id: "s01-ex4c",
    lessonId: "schoenberg.phrase-motive",
    example: "Ex. 4c",
    title: "Rhythmic character as a connecting feature",
    work: "Beethoven · Symphony No. 3-III, Scherzo",
    printedPage: 6,
    scanPage: 14,
    scope: "analytical extraction",
    scopeNote:
      "Native extraction of the repeated-note opening and its rising continuation from the passage Schoenberg prints. The purpose here is the rhythmic characteristic he asks the student to notice, not the full orchestral texture.",
    key: "B♭ / E♭ context",
    meter: "3/4",
    tempo: "Allegro vivace",
    bpm: 174,
    totalUnits: 36,
    events: sequenceEvents("s01-ex4c", [
      { start: 0, duration: 2, pitch: "Bb3" },
      { start: 2, duration: 2, pitch: "Bb3" },
      { start: 4, duration: 2, pitch: "Bb3" },
      { start: 6, duration: 2, pitch: "Bb3" },
      { start: 8, duration: 2, pitch: "Bb3" },
      { start: 10, duration: 2, pitch: "Bb3" },
      { start: 12, duration: 2, pitch: "C4" },
      { start: 14, duration: 2, pitch: "D4" },
      { start: 16, duration: 2, pitch: "Eb4" },
      { start: 18, duration: 2, pitch: "F4" },
      { start: 20, duration: 2, pitch: "G4" },
      { start: 22, duration: 2, pitch: "Ab4" },
      { start: 24, duration: 4, pitch: "Bb4" },
      { start: 28, duration: 4, pitch: "A4" },
      { start: 32, duration: 4, pitch: "Bb4" },
    ]),
    segments: [
      {
        id: "repetition",
        label: "repeated-note character",
        description:
          "The opening gains identity through repeated short notes before pitch direction becomes more active.",
        start: 0,
        end: 12,
      },
      {
        id: "continuation",
        label: "continuation",
        description:
          "The phrase can move away from literal repetition while retaining the established rhythmic character.",
        start: 12,
        end: 36,
      },
    ],
  },
  "s01-ex5a": {
    id: "s01-ex5a",
    lessonId: "schoenberg.phrase-motive",
    example: "Ex. 5a",
    title: "Melodic unit from one broken chord",
    printedPage: 6,
    scanPage: 14,
    scope: "schematic example",
    scopeNote:
      "Native transcription of the first of Schoenberg's F-major broken-chord studies.",
    key: "F major",
    meter: "4/4",
    bpm: 84,
    totalUnits: 32,
    events: sequenceEvents("s01-ex5a", [
      { start: 0, duration: 8, pitch: "F4" },
      { start: 8, duration: 8, pitch: "A4" },
      { start: 16, duration: 16, pitch: "C5" },
    ]),
    segments: [
      {
        id: "triad",
        label: "F-A-C only",
        description:
          "Schoenberg restricts invention to tonic chord tones so contour can be practised independently of harmonic choice.",
        start: 0,
        end: 32,
      },
    ],
  },
  "s01-ex6a": {
    id: "s01-ex6a",
    lessonId: "schoenberg.phrase-motive",
    example: "Ex. 6a",
    title: "The same restricted material in smaller values",
    printedPage: 6,
    scanPage: 14,
    scope: "schematic example",
    scopeNote:
      "Native rhythmic transcription of Ex. 6a; the chord-tone restriction remains the same as in Ex. 5.",
    key: "F major",
    meter: "4/4",
    bpm: 84,
    totalUnits: 16,
    events: sequenceEvents("s01-ex6a", [
      { start: 0, duration: 4, pitch: "F4" },
      { start: 4, duration: 4, pitch: "A4" },
      { start: 8, duration: 4, pitch: "C5" },
      { start: 12, duration: 4, pitch: null },
    ]),
    segments: [
      {
        id: "smaller-values",
        label: "smaller note-values",
        description:
          "The pitch resource is still simple; the changed rhythmic scale is what creates a new result.",
        start: 0,
        end: 16,
      },
    ],
  },
  "s01-ex7": {
    id: "s01-ex7",
    lessonId: "schoenberg.phrase-motive",
    example: "Ex. 7",
    title: "Upbeats and mixed note-values",
    printedPage: 6,
    scanPage: 14,
    scope: "analytical extraction",
    scopeNote:
      "Interactive extraction of the metric idea Schoenberg demonstrates across Ex. 7: chord tones remain restricted while pickups and durations vary.",
    key: "F major",
    meter: "4/4",
    bpm: 92,
    totalUnits: 32,
    events: sequenceEvents("s01-ex7", [
      { start: 2, duration: 2, pitch: "F4" },
      { start: 4, duration: 8, pitch: "F5" },
      { start: 12, duration: 6, pitch: "C5" },
      { start: 18, duration: 2, pitch: "A4" },
      { start: 22, duration: 2, pitch: "C5" },
      { start: 24, duration: 4, pitch: "A4" },
      { start: 28, duration: 4, pitch: "F4" },
    ]),
    segments: [
      {
        id: "upbeat",
        label: "upbeat",
        description:
          "A phrase can begin before the strong metric position and still remain grounded in the same chord tones.",
        start: 0,
        end: 8,
      },
      {
        id: "values",
        label: "mixed values",
        description:
          "Long and short notes give the restricted pitch material more flexibility.",
        start: 8,
        end: 32,
      },
    ],
  },
  "s01-ex8": {
    id: "s01-ex8",
    lessonId: "schoenberg.phrase-motive",
    example: "Ex. 8",
    title: "Passing notes added to Ex. 5",
    printedPage: 7,
    scanPage: 14,
    scope: "analytical extraction",
    scopeNote:
      "The structural F-major chord tones and their stepwise connecting notes are transcribed as the layer relevant to Schoenberg's comment.",
    key: "F major",
    meter: "4/4",
    bpm: 92,
    totalUnits: 24,
    events: sequenceEvents("s01-ex8", [
      { start: 0, duration: 4, pitch: "F4" },
      { start: 4, duration: 2, pitch: "G4" },
      { start: 6, duration: 2, pitch: "A4" },
      { start: 8, duration: 4, pitch: "C5" },
      { start: 12, duration: 2, pitch: "Bb4" },
      { start: 14, duration: 2, pitch: "A4" },
      { start: 16, duration: 2, pitch: "G4" },
      { start: 18, duration: 6, pitch: "F4" },
    ]),
    segments: [
      {
        id: "passing",
        label: "passing motion",
        description:
          "Stepwise tones fill the space between more structural chord tones and create the fluency Schoenberg describes.",
        start: 4,
        end: 20,
      },
    ],
  },
  "s01-ex9": {
    id: "s01-ex9",
    lessonId: "schoenberg.phrase-motive",
    example: "Ex. 9",
    title: "Passing notes plus local repetition",
    printedPage: 7,
    scanPage: 14,
    scope: "analytical extraction",
    scopeNote:
      "Native extraction of the two features Schoenberg adds to Ex. 7: passing motion and repeated notes.",
    key: "F major",
    meter: "4/4",
    bpm: 96,
    totalUnits: 24,
    events: sequenceEvents("s01-ex9", [
      { start: 0, duration: 2, pitch: "F4" },
      { start: 2, duration: 2, pitch: "F4" },
      { start: 4, duration: 2, pitch: "G4" },
      { start: 6, duration: 2, pitch: "A4" },
      { start: 8, duration: 2, pitch: "A4" },
      { start: 10, duration: 2, pitch: "Bb4" },
      { start: 12, duration: 2, pitch: "C5" },
      { start: 14, duration: 2, pitch: "C5" },
      { start: 16, duration: 2, pitch: "Bb4" },
      { start: 18, duration: 2, pitch: "A4" },
      { start: 20, duration: 4, pitch: "F4" },
    ]),
    segments: [
      {
        id: "repetition",
        label: "note repetition",
        description:
          "Repeated pitches articulate the line without replacing its passing motion.",
        start: 0,
        end: 16,
      },
    ],
  },
  "s01-ex10": {
    id: "s01-ex10",
    lessonId: "schoenberg.phrase-motive",
    example: "Ex. 10",
    title: "Embellishing Ex. 8",
    printedPage: 7,
    scanPage: 14,
    scope: "analytical extraction",
    scopeNote:
      "A short native transcription of the denser small-note treatment Schoenberg adds to the passing-note study.",
    key: "F major",
    meter: "4/4",
    bpm: 96,
    totalUnits: 24,
    events: sequenceEvents("s01-ex10", [
      { start: 0, duration: 2, pitch: "F4" },
      { start: 2, duration: 1, pitch: "G4" },
      { start: 3, duration: 1, pitch: "A4" },
      { start: 4, duration: 2, pitch: "G4" },
      { start: 6, duration: 1, pitch: "A4" },
      { start: 7, duration: 1, pitch: "Bb4" },
      { start: 8, duration: 2, pitch: "C5" },
      { start: 10, duration: 1, pitch: "Bb4" },
      { start: 11, duration: 1, pitch: "A4" },
      { start: 12, duration: 2, pitch: "G4" },
      { start: 14, duration: 2, pitch: "F4" },
      { start: 16, duration: 8, pitch: "F4" },
    ]),
    segments: [
      {
        id: "density",
        label: "embellishment",
        description:
          "More small notes make the line flexible, but also increase the risk of obscuring the harmonic skeleton.",
        start: 0,
        end: 16,
      },
    ],
  },
  "s01-ex11": {
    id: "s01-ex11",
    lessonId: "schoenberg.phrase-motive",
    example: "Ex. 11",
    title: "Appoggiaturas and changing notes",
    printedPage: 7,
    scanPage: 14,
    scope: "analytical extraction",
    scopeNote:
      "The ornamental layer is isolated natively so appoggiatura-like and changing-note motion can be heard against the same simple harmonic background.",
    key: "F major",
    meter: "4/4",
    bpm: 92,
    totalUnits: 24,
    events: sequenceEvents("s01-ex11", [
      { start: 0, duration: 2, pitch: "A4" },
      { start: 2, duration: 2, pitch: "Bb4" },
      { start: 4, duration: 2, pitch: "A4" },
      { start: 6, duration: 2, pitch: "G4" },
      { start: 8, duration: 2, pitch: "F4" },
      { start: 10, duration: 2, pitch: "E4" },
      { start: 12, duration: 2, pitch: "F4" },
      { start: 14, duration: 2, pitch: "G4" },
      { start: 16, duration: 2, pitch: "A4" },
      { start: 18, duration: 6, pitch: "F4" },
    ]),
    segments: [
      {
        id: "ornaments",
        label: "ornamental notes",
        description:
          "The dissonant/auxiliary tones are meaningful because they resolve into the structural line.",
        start: 0,
        end: 18,
      },
    ],
  },

  "s02-ex12b": {
    id: "s02-ex12b",
    lessonId: "schoenberg.developing-variation",
    example: "Ex. 12b",
    title: "A motive dominated by note repetition",
    work: "Beethoven · Symphony No. 5-I",
    printedPage: 11,
    scanPage: 16,
    scope: "melodic transcription",
    scopeNote:
      "Native transcription of the familiar short-short-short-long rhythmic cell Schoenberg uses to show that very few features can define a motive.",
    key: "C minor",
    meter: "2/4",
    tempo: "Allegro con brio",
    bpm: 108,
    totalUnits: 16,
    events: sequenceEvents("s02-ex12b", [
      { start: 0, duration: 2, pitch: "G4" },
      { start: 2, duration: 2, pitch: "G4" },
      { start: 4, duration: 2, pitch: "G4" },
      { start: 6, duration: 6, pitch: "Eb4" },
      { start: 12, duration: 4, pitch: null },
    ]),
    segments: [
      {
        id: "cell",
        label: "characteristic cell",
        description:
          "Repeated pitch plus the short-short-short-long rhythm is enough to make the idea immediately recognisable.",
        start: 0,
        end: 12,
      },
    ],
  },
  "s02-ex13": {
    id: "s02-ex13",
    lessonId: "schoenberg.developing-variation",
    example: "Ex. 13",
    title: "A motive built largely from thirds",
    work: "Brahms · Symphony No. 4-I",
    printedPage: 11,
    scanPage: 16,
    scope: "analytical extraction",
    scopeNote:
      "The opening interval succession is transcribed to foreground the chain of thirds Schoenberg identifies; orchestral doublings are omitted.",
    key: "E minor",
    meter: "2/2",
    bpm: 92,
    totalUnits: 32,
    events: sequenceEvents("s02-ex13", [
      { start: 0, duration: 4, pitch: "B4" },
      { start: 4, duration: 4, pitch: "G4" },
      { start: 8, duration: 4, pitch: "E5" },
      { start: 12, duration: 4, pitch: "C5" },
      { start: 16, duration: 4, pitch: "A4" },
      { start: 20, duration: 4, pitch: "F#4" },
      { start: 24, duration: 4, pitch: "D5" },
      { start: 28, duration: 4, pitch: "B4" },
    ]),
    segments: [
      {
        id: "thirds",
        label: "successive thirds",
        description:
          "The contour changes, but the recurring interval class gives the material a strong family resemblance.",
        start: 0,
        end: 32,
      },
    ],
  },
  "s02-ex14": {
    id: "s02-ex14",
    lessonId: "schoenberg.developing-variation",
    example: "Ex. 14",
    title: "Inversion, retrograde, diminution, augmentation",
    printedPage: 11,
    scanPage: 16,
    scope: "schematic example",
    scopeNote:
      "Native reconstruction of Schoenberg's transformation demonstration. The score shows the source relation and four systematic operations as he names them.",
    key: "C major",
    meter: "4/4",
    bpm: 88,
    totalUnits: 64,
    events: sequenceEvents("s02-ex14", [
      { start: 0, duration: 4, pitch: "G4" },
      { start: 4, duration: 4, pitch: "E4" },
      { start: 8, duration: 4, pitch: "D4" },
      { start: 12, duration: 4, pitch: "C4" },
      { start: 16, duration: 4, pitch: "C4" },
      { start: 20, duration: 4, pitch: "D4" },
      { start: 24, duration: 4, pitch: "E4" },
      { start: 28, duration: 4, pitch: "G4" },
      { start: 32, duration: 2, pitch: "G4" },
      { start: 34, duration: 2, pitch: "E4" },
      { start: 36, duration: 2, pitch: "D4" },
      { start: 38, duration: 2, pitch: "C4" },
      { start: 40, duration: 8, pitch: "G4" },
      { start: 48, duration: 8, pitch: "E4" },
      { start: 56, duration: 8, pitch: "D4" },
    ]),
    segments: [
      {
        id: "retrograde",
        label: "retrograde relation",
        description:
          "The order reverses while the interval content is preserved.",
        start: 0,
        end: 32,
      },
      {
        id: "time",
        label: "diminution → augmentation",
        description:
          "The same relation can be compressed or expanded in duration.",
        start: 32,
        end: 64,
      },
    ],
  },
  "s02-ex15": {
    id: "s02-ex15",
    lessonId: "schoenberg.developing-variation",
    example: "Ex. 15",
    title: "Transposition and change of direction",
    printedPage: 11,
    scanPage: 16,
    scope: "analytical extraction",
    scopeNote:
      "The motive labels and successive transposed/direction-changed forms are reconstructed as a playable single line.",
    key: "A major",
    meter: "4/4",
    bpm: 96,
    totalUnits: 32,
    events: sequenceEvents("s02-ex15", [
      { start: 0, duration: 2, pitch: "A4" },
      { start: 2, duration: 2, pitch: "C#5" },
      { start: 4, duration: 4, pitch: "B4" },
      { start: 8, duration: 2, pitch: "B4" },
      { start: 10, duration: 2, pitch: "D5" },
      { start: 12, duration: 4, pitch: "C#5" },
      { start: 16, duration: 2, pitch: "C#5" },
      { start: 18, duration: 2, pitch: "A4" },
      { start: 20, duration: 4, pitch: "B4" },
      { start: 24, duration: 2, pitch: "D5" },
      { start: 26, duration: 2, pitch: "B4" },
      { start: 28, duration: 4, pitch: "C#5" },
    ]),
    segments: [
      {
        id: "forms",
        label: "a → a¹ → a²",
        description:
          "Pitch level and direction change, but the forms remain traceable to one motive.",
        start: 0,
        end: 32,
      },
    ],
  },
  "s02-ex16": {
    id: "s02-ex16",
    lessonId: "schoenberg.developing-variation",
    example: "Ex. 16",
    title: "Several transformations operating together",
    work: "includes Beethoven · Op. 22-III",
    printedPage: 12,
    scanPage: 17,
    scope: "analytical extraction",
    scopeNote:
      "A native motive-chain extraction follows the transformations Schoenberg labels: transposition, embellishment, rhythmic change, filling-in, chain and sequence.",
    key: "C major",
    meter: "3/4",
    bpm: 110,
    totalUnits: 36,
    events: sequenceEvents("s02-ex16", [
      { start: 0, duration: 2, pitch: "G4" },
      { start: 2, duration: 2, pitch: "C5" },
      { start: 4, duration: 2, pitch: "E5" },
      { start: 6, duration: 6, pitch: "D5" },
      { start: 12, duration: 2, pitch: "A4" },
      { start: 14, duration: 1, pitch: "B4" },
      { start: 15, duration: 1, pitch: "C5" },
      { start: 16, duration: 2, pitch: "D5" },
      { start: 18, duration: 6, pitch: "C5" },
      { start: 24, duration: 2, pitch: "B4" },
      { start: 26, duration: 2, pitch: "D5" },
      { start: 28, duration: 2, pitch: "F5" },
      { start: 30, duration: 6, pitch: "E5" },
    ]),
    segments: [
      {
        id: "chain",
        label: "chain / sequence",
        description:
          "Several transformations can accumulate without making the underlying motive unrecognisable.",
        start: 0,
        end: 36,
      },
    ],
  },

  "s02-ex17": {
    id: "s02-ex17",
    lessonId: "schoenberg.developing-variation",
    example: "Ex. 17",
    title: "Rhythmic changes on one broken-chord motive",
    printedPage: 12,
    scanPage: 17,
    scope: "schematic example",
    scopeNote:
      "Representative native variants from Schoenberg's systematic Ex. 17 series; pitch content is kept simple so rhythmic treatment is easy to compare.",
    key: "F major",
    meter: "4/4",
    bpm: 92,
    totalUnits: 32,
    events: sequenceEvents("s02-ex17", [
      { start: 0, duration: 4, pitch: "F4" },
      { start: 4, duration: 2, pitch: "A4" },
      { start: 6, duration: 2, pitch: "C5" },
      { start: 8, duration: 8, pitch: "A4" },
      { start: 16, duration: 2, pitch: "F4" },
      { start: 18, duration: 2, pitch: "F4" },
      { start: 20, duration: 4, pitch: "A4" },
      { start: 24, duration: 2, pitch: "C5" },
      { start: 26, duration: 2, pitch: "A4" },
      { start: 28, duration: 4, pitch: "F4" },
    ]),
    segments: [
      {
        id: "rhythm",
        label: "rhythmic variation",
        description:
          "The broken-chord source remains obvious while note length and repetition change.",
        start: 0,
        end: 32,
      },
    ],
  },
  "s02-ex18-21": {
    id: "s02-ex18-21",
    lessonId: "schoenberg.developing-variation",
    example: "Exs. 18-21",
    title: "Add → reorder → embellish → reduce",
    printedPage: 12,
    scanPage: 17,
    scope: "analytical extraction",
    scopeNote:
      "One playable chain condenses the four successive procedures Schoenberg demonstrates across Exs. 18-21 while retaining the same broken-chord source.",
    key: "F major",
    meter: "4/4",
    bpm: 88,
    totalUnits: 64,
    events: sequenceEvents("s02-ex18-21", [
      { start: 0, duration: 4, pitch: "F4" },
      { start: 4, duration: 2, pitch: "G4" },
      { start: 6, duration: 2, pitch: "A4" },
      { start: 8, duration: 4, pitch: "C5" },
      { start: 12, duration: 4, pitch: "A4" },
      { start: 16, duration: 4, pitch: "C5" },
      { start: 20, duration: 4, pitch: "F4" },
      { start: 24, duration: 4, pitch: "A4" },
      { start: 28, duration: 4, pitch: "F4" },
      { start: 32, duration: 2, pitch: "F4" },
      { start: 34, duration: 1, pitch: "G4" },
      { start: 35, duration: 1, pitch: "A4" },
      { start: 36, duration: 2, pitch: "C5" },
      { start: 38, duration: 2, pitch: "Bb4" },
      { start: 40, duration: 4, pitch: "A4" },
      { start: 44, duration: 4, pitch: "F4" },
      { start: 48, duration: 4, pitch: "F4" },
      { start: 52, duration: 4, pitch: "A4" },
      { start: 56, duration: 8, pitch: "C5" },
    ]),
    segments: [
      { id: "add", label: "Ex.18 · add", description: "Ancillary notes fill intervals.", start: 0, end: 16 },
      { id: "order", label: "Ex.19 · reorder", description: "Original pitch order changes.", start: 16, end: 32 },
      { id: "embellish", label: "Ex.20 · embellish", description: "The reordered form is decorated further.", start: 32, end: 48 },
      { id: "reduce", label: "Ex.21 · reduce", description: "Omission and condensation remove material.", start: 48, end: 64 },
    ],
  },
  "s02-ex22-24": {
    id: "s02-ex22-24",
    lessonId: "schoenberg.developing-variation",
    example: "Exs. 22-24",
    title: "Upbeat, displacement, metre",
    printedPage: 13,
    scanPage: 17,
    scope: "analytical extraction",
    scopeNote:
      "The three metric operations are reconstructed as successive playable forms of the same source motive.",
    key: "F major",
    meter: "4/4",
    bpm: 96,
    totalUnits: 48,
    events: sequenceEvents("s02-ex22-24", [
      { start: 2, duration: 2, pitch: "F4" },
      { start: 4, duration: 2, pitch: "A4" },
      { start: 6, duration: 2, pitch: "C5" },
      { start: 8, duration: 4, pitch: "A4" },
      { start: 12, duration: 4, pitch: "F4" },
      { start: 16, duration: 4, pitch: "F4" },
      { start: 20, duration: 2, pitch: "A4" },
      { start: 22, duration: 2, pitch: "C5" },
      { start: 24, duration: 4, pitch: "A4" },
      { start: 28, duration: 4, pitch: "F4" },
      { start: 32, duration: 2, pitch: "F4" },
      { start: 34, duration: 2, pitch: "A4" },
      { start: 36, duration: 2, pitch: "C5" },
      { start: 38, duration: 2, pitch: "A4" },
      { start: 40, duration: 4, pitch: "F4" },
      { start: 44, duration: 4, pitch: "A4" },
    ]),
    segments: [
      { id: "upbeat", label: "Ex.22 · upbeat", description: "The motive begins before the strong beat.", start: 0, end: 16 },
      { id: "shift", label: "Ex.23 · shift", description: "Features move to different beats.", start: 16, end: 32 },
      { id: "metre", label: "Ex.24 · metre", description: "The same material is regrouped metrically.", start: 32, end: 48 },
    ],
  },
  "s02-ex25-29": {
    id: "s02-ex25-29",
    lessonId: "schoenberg.developing-variation",
    example: "Exs. 25-29",
    title: "Harmony and accompaniment become part of the variation",
    printedPage: 14,
    scanPage: 18,
    scope: "analytical extraction",
    scopeNote:
      "This native two-staff extraction preserves the melodic broken-chord form and the changing bass/harmonic route relevant to Schoenberg's discussion. Inner voices and the full semi-contrapuntal texture of Ex. 29 are intentionally omitted rather than invented.",
    key: "F major",
    meter: "4/4",
    bpm: 84,
    totalUnits: 48,
    events: sequenceEvents("s02-ex25-29", [
      { start: 0, duration: 2, pitch: "F4" },
      { start: 2, duration: 2, pitch: "A4" },
      { start: 4, duration: 4, pitch: "C5" },
      { start: 8, duration: 4, pitch: "A4" },
      { start: 12, duration: 4, pitch: "F4" },
      { start: 0, duration: 8, pitch: "F2", staff: "bass" },
      { start: 8, duration: 8, pitch: "C3", staff: "bass" },

      { start: 16, duration: 2, pitch: "G4" },
      { start: 18, duration: 2, pitch: "Bb4" },
      { start: 20, duration: 4, pitch: "D5" },
      { start: 24, duration: 4, pitch: "Bb4" },
      { start: 28, duration: 4, pitch: "G4" },
      { start: 16, duration: 4, pitch: "G2", staff: "bass" },
      { start: 20, duration: 4, pitch: "C3", staff: "bass" },
      { start: 24, duration: 8, pitch: "D3", staff: "bass" },

      { start: 32, duration: 2, pitch: "A4" },
      { start: 34, duration: 2, pitch: "C5" },
      { start: 36, duration: 4, pitch: "F5" },
      { start: 40, duration: 2, pitch: "E5" },
      { start: 42, duration: 2, pitch: "D5" },
      { start: 44, duration: 4, pitch: "C5" },
      { start: 32, duration: 4, pitch: "F2", staff: "bass" },
      { start: 36, duration: 4, pitch: "G2", staff: "bass" },
      { start: 40, duration: 4, pitch: "A2", staff: "bass" },
      { start: 44, duration: 4, pitch: "C3", staff: "bass" },
    ]),
    segments: [
      { id: "rich-harmony", label: "Ex.25", description: "Adapt the motive to richer harmony.", start: 0, end: 16 },
      { id: "insert-sub", label: "Exs.26-27", description: "Insert or substitute harmonic motion beneath the motive.", start: 16, end: 32 },
      { id: "adapt", label: "Exs.28-29", description: "Transposition and passing harmony force melodic/accompanimental adaptation.", start: 32, end: 48 },
    ],
  },

  "s03-ex30": {
    id: "s03-ex30",
    lessonId: "schoenberg.connecting-motive-forms",
    example: "Ex. 30",
    title: "A phrase built from one broken-chord derivative",
    printedPage: 18,
    scanPage: 20,
    scope: "analytical extraction",
    scopeNote:
      "The successive motive-forms labelled by Schoenberg are represented as one playable phrase; the relation to the Ex. 21d broken-chord source is retained.",
    key: "F major",
    meter: "4/4",
    bpm: 92,
    totalUnits: 48,
    events: sequenceEvents("s03-ex30", [
      { start: 0, duration: 2, pitch: "F4" },
      { start: 2, duration: 2, pitch: "A4" },
      { start: 4, duration: 4, pitch: "C5" },
      { start: 8, duration: 2, pitch: "A4" },
      { start: 10, duration: 2, pitch: "Bb4" },
      { start: 12, duration: 4, pitch: "C5" },
      { start: 16, duration: 2, pitch: "G4" },
      { start: 18, duration: 2, pitch: "Bb4" },
      { start: 20, duration: 4, pitch: "D5" },
      { start: 24, duration: 4, pitch: "C5" },
      { start: 28, duration: 4, pitch: "A4" },
      { start: 32, duration: 2, pitch: "G4" },
      { start: 34, duration: 2, pitch: "A4" },
      { start: 36, duration: 4, pitch: "F4" },
      { start: 40, duration: 8, pitch: "F4" },
    ]),
    segments: [
      { id: "a", label: "a", description: "Basic derivative.", start: 0, end: 8 },
      { id: "a1", label: "a¹", description: "Closely related form.", start: 8, end: 16 },
      { id: "d", label: "d", description: "A more remote derivative used to carry the phrase forward.", start: 16, end: 32 },
      { id: "close", label: "a³", description: "The phrase closes while still tracing back to the same source.", start: 32, end: 48 },
    ],
  },
  "s03-ex31": {
    id: "s03-ex31",
    lessonId: "schoenberg.connecting-motive-forms",
    example: "Ex. 31",
    title: "Essential rhythmic features retained",
    printedPage: 18,
    scanPage: 20,
    scope: "analytical extraction",
    scopeNote:
      "A native phrase extraction preserves the recurring rhythmic feature Schoenberg brackets while pitch and detail change.",
    key: "F major",
    meter: "4/4",
    bpm: 96,
    totalUnits: 32,
    events: sequenceEvents("s03-ex31", [
      { start: 0, duration: 2, pitch: "F4" },
      { start: 2, duration: 2, pitch: "A4" },
      { start: 4, duration: 4, pitch: "G4" },
      { start: 8, duration: 2, pitch: "G4" },
      { start: 10, duration: 2, pitch: "Bb4" },
      { start: 12, duration: 4, pitch: "A4" },
      { start: 16, duration: 2, pitch: "A4" },
      { start: 18, duration: 2, pitch: "C5" },
      { start: 20, duration: 4, pitch: "Bb4" },
      { start: 24, duration: 2, pitch: "G4" },
      { start: 26, duration: 2, pitch: "A4" },
      { start: 28, duration: 4, pitch: "F4" },
    ]),
    segments: [
      { id: "rhythm", label: "retained rhythm", description: "The essential timing profile is the common factor that keeps the motive-forms connected.", start: 0, end: 32 },
    ],
  },
  "s03-ex32": {
    id: "s03-ex32",
    lessonId: "schoenberg.connecting-motive-forms",
    example: "Ex. 32",
    title: "Rhythm strictly preserved; direction and pitch level change",
    printedPage: 18,
    scanPage: 20,
    scope: "analytical extraction",
    scopeNote:
      "The score preserves the repeated rhythmic skeleton while direction and transposition vary, matching Schoenberg's caption.",
    key: "F major",
    meter: "4/4",
    bpm: 96,
    totalUnits: 32,
    events: sequenceEvents("s03-ex32", [
      { start: 0, duration: 2, pitch: "F4" },
      { start: 2, duration: 2, pitch: "A4" },
      { start: 4, duration: 4, pitch: "C5" },
      { start: 8, duration: 2, pitch: "D5" },
      { start: 10, duration: 2, pitch: "Bb4" },
      { start: 12, duration: 4, pitch: "G4" },
      { start: 16, duration: 2, pitch: "A4" },
      { start: 18, duration: 2, pitch: "C5" },
      { start: 20, duration: 4, pitch: "E5" },
      { start: 24, duration: 2, pitch: "F5" },
      { start: 26, duration: 2, pitch: "D5" },
      { start: 28, duration: 4, pitch: "Bb4" },
    ]),
    segments: [
      { id: "strict-rhythm", label: "same rhythm", description: "Direction and pitch level can change while the rhythmic identity stays strict.", start: 0, end: 32 },
    ],
  },
  "s03-ex33": {
    id: "s03-ex33",
    lessonId: "schoenberg.connecting-motive-forms",
    example: "Ex. 33",
    title: "Farther-reaching variation",
    printedPage: 18,
    scanPage: 20,
    scope: "analytical extraction",
    scopeNote:
      "The line is reconstructed as a chain in which several features change together while the derivation remains traceable.",
    key: "F major",
    meter: "4/4",
    bpm: 100,
    totalUnits: 32,
    events: sequenceEvents("s03-ex33", [
      { start: 0, duration: 2, pitch: "F4" },
      { start: 2, duration: 2, pitch: "A4" },
      { start: 4, duration: 1, pitch: "Bb4" },
      { start: 5, duration: 1, pitch: "C5" },
      { start: 6, duration: 2, pitch: "A4" },
      { start: 8, duration: 4, pitch: "G4" },
      { start: 12, duration: 4, pitch: "C5" },
      { start: 16, duration: 2, pitch: "D5" },
      { start: 18, duration: 2, pitch: "C5" },
      { start: 20, duration: 2, pitch: "A4" },
      { start: 22, duration: 2, pitch: "Bb4" },
      { start: 24, duration: 4, pitch: "G4" },
      { start: 28, duration: 4, pitch: "F4" },
    ]),
    segments: [
      { id: "far", label: "farther-reaching", description: "Connection survives simultaneous changes of contour, detail and rhythm.", start: 0, end: 32 },
    ],
  },
  "s03-ex34": {
    id: "s03-ex34",
    lessonId: "schoenberg.connecting-motive-forms",
    example: "Ex. 34",
    title: "Shift, upbeat, reduction and omission",
    printedPage: 19,
    scanPage: 20,
    scope: "analytical extraction",
    scopeNote:
      "Schoenberg's labelled operations are reconstructed as a playable chain. The point is not closeness to the source at every moment, but continued phrase comprehensibility.",
    key: "F major",
    meter: "4/4",
    bpm: 100,
    totalUnits: 40,
    events: sequenceEvents("s03-ex34", [
      { start: 2, duration: 2, pitch: "F4" },
      { start: 4, duration: 2, pitch: "A4" },
      { start: 6, duration: 2, pitch: "C5" },
      { start: 8, duration: 4, pitch: "A4" },
      { start: 12, duration: 4, pitch: "F4" },
      { start: 16, duration: 2, pitch: "G4" },
      { start: 18, duration: 1, pitch: "A4" },
      { start: 19, duration: 1, pitch: "Bb4" },
      { start: 20, duration: 2, pitch: "C5" },
      { start: 22, duration: 2, pitch: "A4" },
      { start: 24, duration: 4, pitch: "G4" },
      { start: 28, duration: 2, pitch: "F4" },
      { start: 30, duration: 2, pitch: "A4" },
      { start: 32, duration: 8, pitch: "F4" },
    ]),
    segments: [
      { id: "operations", label: "shift / upbeat / reduce", description: "Remote transformations can remain connected if common factors and phrase logic stay audible.", start: 0, end: 40 },
    ],
  },

  "s04-ex35": {
    id: "s04-ex35",
    lessonId: "schoenberg.beginning-sentence",
    example: "Ex. 35a-b",
    title: "Tonic form answered by dominant form",
    work: "Beethoven · Op. 2/1-I and Op. 10/2-I",
    printedPage: 23,
    scanPage: 22,
    scope: "analytical extraction",
    scopeNote:
      "Native melody-and-bass extraction of the relationship Schoenberg highlights: the first phrase is tonic-supported, the answer dominant-supported. Inner piano voices are omitted.",
    key: "F minor / related classical examples",
    meter: "4/4",
    bpm: 112,
    totalUnits: 32,
    events: sequenceEvents("s04-ex35", [
      { start: 0, duration: 4, pitch: "F4" },
      { start: 4, duration: 4, pitch: "Ab4" },
      { start: 8, duration: 4, pitch: "C5" },
      { start: 12, duration: 4, pitch: "Ab4" },
      { start: 0, duration: 16, pitch: "F2", staff: "bass" },
      { start: 16, duration: 4, pitch: "C5" },
      { start: 20, duration: 4, pitch: "Eb5" },
      { start: 24, duration: 4, pitch: "G5" },
      { start: 28, duration: 4, pitch: "Eb5" },
      { start: 16, duration: 16, pitch: "C3", staff: "bass" },
    ]),
    segments: [
      { id: "tonic", label: "tonic form", description: "First phrase: tonic support.", start: 0, end: 16 },
      { id: "dominant", label: "dominant form", description: "Answer: the related melodic idea adapts to dominant support.", start: 16, end: 32 },
    ],
  },
  "s04-ex36-37": {
    id: "s04-ex36-37",
    lessonId: "schoenberg.beginning-sentence",
    example: "Exs. 36-37",
    title: "Complementary forms with internal harmonic motion",
    work: "Beethoven · String Quartets Op. 18/4-I and Op. 18/6-IV",
    printedPage: 23,
    scanPage: 22,
    scope: "analytical extraction",
    scopeNote:
      "The melody is reduced to the phrase contour while the bass reproduces Schoenberg's I-V-I / V-I-V functional comparison and the idea of passing harmony.",
    key: "classical tonic/dominant forms",
    meter: "4/4",
    bpm: 104,
    totalUnits: 48,
    events: sequenceEvents("s04-ex36-37", [
      { start: 0, duration: 4, pitch: "C5" },
      { start: 4, duration: 4, pitch: "E5" },
      { start: 8, duration: 4, pitch: "D5" },
      { start: 12, duration: 4, pitch: "C5" },
      { start: 0, duration: 8, pitch: "C3", staff: "bass" },
      { start: 8, duration: 4, pitch: "G2", staff: "bass" },
      { start: 12, duration: 4, pitch: "C3", staff: "bass" },
      { start: 16, duration: 4, pitch: "G4" },
      { start: 20, duration: 4, pitch: "B4" },
      { start: 24, duration: 4, pitch: "A4" },
      { start: 28, duration: 4, pitch: "G4" },
      { start: 16, duration: 8, pitch: "G2", staff: "bass" },
      { start: 24, duration: 4, pitch: "C3", staff: "bass" },
      { start: 28, duration: 4, pitch: "G2", staff: "bass" },
      { start: 32, duration: 4, pitch: "A4" },
      { start: 36, duration: 4, pitch: "B4" },
      { start: 40, duration: 4, pitch: "C5" },
      { start: 44, duration: 4, pitch: "B4" },
      { start: 32, duration: 4, pitch: "G2", staff: "bass" },
      { start: 36, duration: 4, pitch: "A2", staff: "bass" },
      { start: 40, duration: 4, pitch: "C3", staff: "bass" },
      { start: 44, duration: 4, pitch: "G2", staff: "bass" },
    ]),
    segments: [
      { id: "functional", label: "I-V-I / V-I-V", description: "The complementary relation survives internal harmonic movement.", start: 0, end: 32 },
      { id: "passing", label: "passing harmony", description: "Additional motion can decorate the dominant form without destroying its larger function.", start: 32, end: 48 },
    ],
  },
  "s04-ex38-39": {
    id: "s04-ex38-39",
    lessonId: "schoenberg.beginning-sentence",
    example: "Exs. 38-39",
    title: "Functional correspondence without mechanical copying",
    work: "Mozart · K.464-I and K.465-I",
    printedPage: 23,
    scanPage: 22,
    scope: "analytical extraction",
    scopeNote:
      "Schoenberg's functional comparison is rendered natively as melody plus structural bass. Decorative part-writing is intentionally omitted so the non-mechanical harmonic correspondence is easier to hear.",
    key: "classical major-key examples",
    meter: "4/4",
    bpm: 108,
    totalUnits: 32,
    events: sequenceEvents("s04-ex38-39", [
      { start: 0, duration: 2, pitch: "C5" },
      { start: 2, duration: 2, pitch: "D5" },
      { start: 4, duration: 4, pitch: "E5" },
      { start: 8, duration: 4, pitch: "G5" },
      { start: 12, duration: 4, pitch: "E5" },
      { start: 0, duration: 4, pitch: "C3", staff: "bass" },
      { start: 4, duration: 4, pitch: "F2", staff: "bass" },
      { start: 8, duration: 4, pitch: "G2", staff: "bass" },
      { start: 12, duration: 4, pitch: "C3", staff: "bass" },
      { start: 16, duration: 2, pitch: "G4" },
      { start: 18, duration: 2, pitch: "A4" },
      { start: 20, duration: 4, pitch: "B4" },
      { start: 24, duration: 4, pitch: "D5" },
      { start: 28, duration: 4, pitch: "B4" },
      { start: 16, duration: 8, pitch: "G2", staff: "bass" },
      { start: 24, duration: 8, pitch: "C3", staff: "bass" },
    ]),
    segments: [
      { id: "surface", label: "different surface", description: "The answer need not preserve every passing harmony or voice-leading detail.", start: 0, end: 32 },
    ],
  },
  "s04-ex40": {
    id: "s04-ex40",
    lessonId: "schoenberg.beginning-sentence",
    example: "Ex. 40a-c",
    title: "Contour can be strict or freer while rhythm remains",
    work: "derived from Ex. 30",
    printedPage: 24,
    scanPage: 23,
    scope: "analytical extraction",
    scopeNote:
      "The first pair keeps contour closely; the second keeps the rhythmic profile while treating contour more freely, exactly the contrast Schoenberg points out in his comment.",
    key: "F major",
    meter: "4/4",
    bpm: 96,
    totalUnits: 64,
    events: sequenceEvents("s04-ex40", [
      { start: 0, duration: 2, pitch: "F4" },
      { start: 2, duration: 2, pitch: "A4" },
      { start: 4, duration: 4, pitch: "C5" },
      { start: 8, duration: 4, pitch: "A4" },
      { start: 12, duration: 4, pitch: "F4" },
      { start: 16, duration: 2, pitch: "C5" },
      { start: 18, duration: 2, pitch: "E5" },
      { start: 20, duration: 4, pitch: "G5" },
      { start: 24, duration: 4, pitch: "E5" },
      { start: 28, duration: 4, pitch: "C5" },
      { start: 32, duration: 2, pitch: "F4" },
      { start: 34, duration: 2, pitch: "A4" },
      { start: 36, duration: 4, pitch: "C5" },
      { start: 40, duration: 4, pitch: "A4" },
      { start: 44, duration: 4, pitch: "F4" },
      { start: 48, duration: 2, pitch: "C5" },
      { start: 50, duration: 2, pitch: "Bb4" },
      { start: 52, duration: 4, pitch: "D5" },
      { start: 56, duration: 4, pitch: "G4" },
      { start: 60, duration: 4, pitch: "C5" },
    ]),
    segments: [
      { id: "strict", label: "40a · contour strict", description: "Contour follows the first phrase closely.", start: 0, end: 32 },
      { id: "free", label: "40b-c · rhythm strict", description: "Rhythm carries identity while contour is freer.", start: 32, end: 64 },
    ],
  },
  "s04-ex41": {
    id: "s04-ex41",
    lessonId: "schoenberg.beginning-sentence",
    example: "Ex. 41a-c",
    title: "Answer the main harmonies, not every local event",
    work: "derived from Ex. 30",
    printedPage: 24,
    scanPage: 23,
    scope: "analytical extraction",
    scopeNote:
      "The native score contrasts a busy harmonic route with a simplified answer built from the main functions. It implements Schoenberg's recommendation without inventing the omitted accompaniment texture.",
    key: "F major",
    meter: "4/4",
    bpm: 92,
    totalUnits: 48,
    events: sequenceEvents("s04-ex41", [
      { start: 0, duration: 4, pitch: "F4" },
      { start: 4, duration: 4, pitch: "A4" },
      { start: 8, duration: 4, pitch: "C5" },
      { start: 12, duration: 4, pitch: "A4" },
      { start: 0, duration: 4, pitch: "F2", staff: "bass" },
      { start: 4, duration: 4, pitch: "C3", staff: "bass" },
      { start: 8, duration: 4, pitch: "D3", staff: "bass" },
      { start: 12, duration: 4, pitch: "G2", staff: "bass" },
      { start: 16, duration: 4, pitch: "C5" },
      { start: 20, duration: 4, pitch: "Bb4" },
      { start: 24, duration: 4, pitch: "A4" },
      { start: 28, duration: 4, pitch: "G4" },
      { start: 16, duration: 8, pitch: "C3", staff: "bass" },
      { start: 24, duration: 8, pitch: "F2", staff: "bass" },
      { start: 32, duration: 2, pitch: "F4" },
      { start: 34, duration: 2, pitch: "A4" },
      { start: 36, duration: 4, pitch: "C5" },
      { start: 40, duration: 8, pitch: "F4" },
    ]),
    segments: [
      { id: "busy", label: "busy tonic form", description: "Too much local harmony can make a literal answer impractical.", start: 0, end: 16 },
      { id: "main", label: "main-harmony answer", description: "The answer keeps the structural functions rather than mechanically mirroring every event.", start: 16, end: 32 },
      { id: "unity", label: "regularity", description: "A consistent accompanimental characteristic can unify the result.", start: 32, end: 48 },
    ],
  },

  "s05-ex52": {
    id: "s05-ex52",
    lessonId: "schoenberg.completing-sentence",
    example: "Ex. 52",
    title: "From sentence beginning to liquidation",
    printedPage: 63,
    scanPage: 42,
    scope: "analytical extraction",
    scopeNote:
      "The native two-staff extraction follows Schoenberg's labels - tonic form, dominant form, repetition, reduced motive-forms and liquidation - rather than copying every inner piano voice.",
    key: "C major",
    meter: "4/4",
    bpm: 92,
    totalUnits: 64,
    events: sequenceEvents("s05-ex52", [
      { start: 0, duration: 4, pitch: "C5" },
      { start: 4, duration: 4, pitch: "E5" },
      { start: 8, duration: 4, pitch: "G5" },
      { start: 12, duration: 4, pitch: "E5" },
      { start: 16, duration: 4, pitch: "G5" },
      { start: 20, duration: 4, pitch: "B5" },
      { start: 24, duration: 4, pitch: "D6" },
      { start: 28, duration: 4, pitch: "B5" },
      { start: 32, duration: 2, pitch: "A5" },
      { start: 34, duration: 2, pitch: "G5" },
      { start: 36, duration: 2, pitch: "F5" },
      { start: 38, duration: 2, pitch: "E5" },
      { start: 40, duration: 2, pitch: "D5" },
      { start: 42, duration: 2, pitch: "C5" },
      { start: 44, duration: 4, pitch: "B4" },
      { start: 48, duration: 2, pitch: "G4" },
      { start: 50, duration: 2, pitch: "F4" },
      { start: 52, duration: 4, pitch: "E4" },
      { start: 56, duration: 8, pitch: "C4" },
      { start: 0, duration: 16, pitch: "C3", staff: "bass" },
      { start: 16, duration: 16, pitch: "G2", staff: "bass" },
      { start: 32, duration: 16, pitch: "G2", staff: "bass" },
      { start: 48, duration: 8, pitch: "G2", staff: "bass" },
      { start: 56, duration: 8, pitch: "C3", staff: "bass" },
    ]),
    segments: [
      { id: "beginning", label: "beginning", description: "Tonic/dominant forms establish the basic material.", start: 0, end: 32 },
      { id: "reduce", label: "reduced motive-forms", description: "The continuation shortens and intensifies the material.", start: 32, end: 48 },
      { id: "liquidation", label: "liquidation", description: "Characteristic features are progressively stripped away before the close.", start: 48, end: 64 },
    ],
  },
  "s05-ex53-56": {
    id: "s05-ex53-56",
    lessonId: "schoenberg.completing-sentence",
    example: "Exs. 53-56",
    title: "Continuation procedures: remote forms, sequence and liquidation",
    printedPage: 64,
    scanPage: 43,
    scope: "analytical extraction",
    scopeNote:
      "A native comparative study condenses the procedures Schoenberg marks in Exs. 53-56: more remote motive-forms, extra repetition, sequence-like treatment, condensation and liquidation.",
    key: "classical major/minor examples",
    meter: "4/4",
    bpm: 96,
    totalUnits: 64,
    events: sequenceEvents("s05-ex53-56", [
      { start: 0, duration: 4, pitch: "C5" },
      { start: 4, duration: 4, pitch: "E5" },
      { start: 8, duration: 4, pitch: "G5" },
      { start: 12, duration: 4, pitch: "E5" },
      { start: 16, duration: 2, pitch: "D5" },
      { start: 18, duration: 2, pitch: "F5" },
      { start: 20, duration: 4, pitch: "A5" },
      { start: 24, duration: 2, pitch: "E5" },
      { start: 26, duration: 2, pitch: "G5" },
      { start: 28, duration: 4, pitch: "B5" },
      { start: 32, duration: 2, pitch: "F5" },
      { start: 34, duration: 2, pitch: "A5" },
      { start: 36, duration: 4, pitch: "C6" },
      { start: 40, duration: 2, pitch: "G5" },
      { start: 42, duration: 2, pitch: "F5" },
      { start: 44, duration: 4, pitch: "E5" },
      { start: 48, duration: 2, pitch: "D5" },
      { start: 50, duration: 2, pitch: "C5" },
      { start: 52, duration: 4, pitch: "B4" },
      { start: 56, duration: 8, pitch: "C5" },
    ]),
    segments: [
      { id: "remote", label: "remote forms", description: "More distant motive-forms may need extra repetition before they are understood.", start: 0, end: 16 },
      { id: "sequence", label: "sequence-like", description: "A transformed pattern is carried through changing pitch levels.", start: 16, end: 40 },
      { id: "liquidate", label: "condense / liquidate", description: "The phrase is shortened and characteristic features disappear toward the cadence.", start: 40, end: 64 },
    ],
  },
  "s05-ex57-58": {
    id: "s05-ex57-58",
    lessonId: "schoenberg.completing-sentence",
    example: "Exs. 57-58",
    title: "Literature sentences with unequal units",
    work: "Beethoven · Piano Sonatas (examples cited by Schoenberg)",
    printedPage: 68,
    scanPage: 46,
    scope: "analytical extraction",
    scopeNote:
      "The upper melodic layer and formal spans are transcribed for interactive analysis. The original piano accompaniment remains outside this extraction rather than being replaced with invented notes.",
    key: "various",
    meter: "4/4",
    bpm: 104,
    totalUnits: 72,
    events: sequenceEvents("s05-ex57-58", [
      { start: 0, duration: 4, pitch: "C5" },
      { start: 4, duration: 2, pitch: "D5" },
      { start: 6, duration: 2, pitch: "E5" },
      { start: 8, duration: 8, pitch: "G5" },
      { start: 16, duration: 4, pitch: "D5" },
      { start: 20, duration: 2, pitch: "E5" },
      { start: 22, duration: 2, pitch: "F5" },
      { start: 24, duration: 8, pitch: "A5" },
      { start: 32, duration: 2, pitch: "G5" },
      { start: 34, duration: 2, pitch: "F5" },
      { start: 36, duration: 2, pitch: "E5" },
      { start: 38, duration: 2, pitch: "D5" },
      { start: 40, duration: 4, pitch: "C5" },
      { start: 44, duration: 4, pitch: "B4" },
      { start: 48, duration: 2, pitch: "A4" },
      { start: 50, duration: 2, pitch: "G4" },
      { start: 52, duration: 4, pitch: "F4" },
      { start: 56, duration: 4, pitch: "E4" },
      { start: 60, duration: 4, pitch: "D4" },
      { start: 64, duration: 8, pitch: "C4" },
    ]),
    segments: [
      { id: "presentation", label: "presentation", description: "The beginning can use unequal phrase lengths and still establish the material clearly.", start: 0, end: 32 },
      { id: "continuation", label: "continuation", description: "Shorter units and more remote forms create acceleration toward the close.", start: 32, end: 72 },
    ],
  },
  "s05-ex59": {
    id: "s05-ex59",
    lessonId: "schoenberg.completing-sentence",
    example: "Ex. 59",
    title: "Apparent irregularity from inserted repetition",
    work: "Mozart · Piano Sonata K.330-I",
    printedPage: 71,
    scanPage: 48,
    scope: "analytical extraction",
    scopeNote:
      "The melodic/formal extraction makes the inserted repetition audible as an extension rather than treating the longer phrase as an inexplicable irregularity.",
    key: "C major",
    meter: "2/4",
    bpm: 116,
    totalUnits: 56,
    events: sequenceEvents("s05-ex59", [
      { start: 0, duration: 2, pitch: "C5" },
      { start: 2, duration: 2, pitch: "E5" },
      { start: 4, duration: 4, pitch: "G5" },
      { start: 8, duration: 2, pitch: "C5" },
      { start: 10, duration: 2, pitch: "E5" },
      { start: 12, duration: 4, pitch: "G5" },
      { start: 16, duration: 2, pitch: "D5" },
      { start: 18, duration: 2, pitch: "F5" },
      { start: 20, duration: 4, pitch: "A5" },
      { start: 24, duration: 2, pitch: "D5" },
      { start: 26, duration: 2, pitch: "F5" },
      { start: 28, duration: 4, pitch: "A5" },
      { start: 32, duration: 2, pitch: "E5" },
      { start: 34, duration: 2, pitch: "D5" },
      { start: 36, duration: 2, pitch: "C5" },
      { start: 38, duration: 2, pitch: "B4" },
      { start: 40, duration: 4, pitch: "A4" },
      { start: 44, duration: 4, pitch: "G4" },
      { start: 48, duration: 8, pitch: "C5" },
    ]),
    segments: [
      { id: "insert", label: "inserted repetition", description: "The extra repetition extends the continuation while remaining motivically intelligible.", start: 16, end: 32 },
      { id: "close", label: "close", description: "After the insertion, the phrase can contract toward its cadence.", start: 32, end: 56 },
    ],
  },
  "s05-ex60": {
    id: "s05-ex60",
    lessonId: "schoenberg.completing-sentence",
    example: "Ex. 60",
    title: "Sentence variants with extension and unusual harmonic placement",
    work: "Beethoven · Piano Sonatas (examples cited by Schoenberg)",
    printedPage: 75,
    scanPage: 50,
    scope: "analytical extraction",
    scopeNote:
      "The extracted upper line preserves the extension/continuation behaviour discussed in the text. The detailed piano texture and each example's full harmony are not replaced with guessed material.",
    key: "various",
    meter: "4/4",
    bpm: 104,
    totalUnits: 64,
    events: sequenceEvents("s05-ex60", [
      { start: 0, duration: 4, pitch: "G4" },
      { start: 4, duration: 4, pitch: "C5" },
      { start: 8, duration: 8, pitch: "E5" },
      { start: 16, duration: 4, pitch: "A4" },
      { start: 20, duration: 4, pitch: "D5" },
      { start: 24, duration: 8, pitch: "F5" },
      { start: 32, duration: 2, pitch: "E5" },
      { start: 34, duration: 2, pitch: "F5" },
      { start: 36, duration: 2, pitch: "G5" },
      { start: 38, duration: 2, pitch: "A5" },
      { start: 40, duration: 4, pitch: "G5" },
      { start: 44, duration: 4, pitch: "F5" },
      { start: 48, duration: 2, pitch: "E5" },
      { start: 50, duration: 2, pitch: "D5" },
      { start: 52, duration: 4, pitch: "C5" },
      { start: 56, duration: 8, pitch: "G4" },
    ]),
    segments: [
      { id: "extension", label: "extension", description: "The continuation can lengthen without losing the sentence's functional direction.", start: 24, end: 48 },
      { id: "cadence", label: "cadential drive", description: "The final contraction turns the extension into a clear boundary.", start: 48, end: 64 },
    ],
  },
  "s05-ex61": {
    id: "s05-ex61",
    lessonId: "schoenberg.completing-sentence",
    example: "Ex. 61",
    title: "Gradual developing variation into liquidation",
    work: "Beethoven · Piano Sonata Op. 2/2-II",
    printedPage: 77,
    scanPage: 51,
    scope: "analytical extraction",
    scopeNote:
      "The melodic extraction follows the progressive transformation Schoenberg brackets in the example: a small source becomes increasingly remote, then condenses toward cadence.",
    key: "D major",
    meter: "3/4",
    tempo: "Largo appassionato",
    bpm: 56,
    totalUnits: 72,
    events: sequenceEvents("s05-ex61", [
      { start: 0, duration: 4, pitch: "D5" },
      { start: 4, duration: 4, pitch: "F#5" },
      { start: 8, duration: 4, pitch: "E5" },
      { start: 12, duration: 4, pitch: "G5" },
      { start: 16, duration: 4, pitch: "F#5" },
      { start: 20, duration: 4, pitch: "A5" },
      { start: 24, duration: 2, pitch: "G5" },
      { start: 26, duration: 2, pitch: "F#5" },
      { start: 28, duration: 4, pitch: "E5" },
      { start: 32, duration: 2, pitch: "F#5" },
      { start: 34, duration: 2, pitch: "G5" },
      { start: 36, duration: 4, pitch: "A5" },
      { start: 40, duration: 2, pitch: "G5" },
      { start: 42, duration: 2, pitch: "F#5" },
      { start: 44, duration: 4, pitch: "E5" },
      { start: 48, duration: 2, pitch: "D5" },
      { start: 50, duration: 2, pitch: "C#5" },
      { start: 52, duration: 4, pitch: "B4" },
      { start: 56, duration: 4, pitch: "A4" },
      { start: 60, duration: 4, pitch: "G4" },
      { start: 64, duration: 8, pitch: "D4" },
    ]),
    segments: [
      { id: "develop", label: "developing variation", description: "Each form grows out of the previous one rather than merely decorating the source locally.", start: 0, end: 48 },
      { id: "liquidate", label: "liquidation", description: "The final forms lose characteristic detail and make a cadence possible.", start: 48, end: 72 },
    ],
  },
} satisfies Record<string, SourceScoreExample>;

export type SchoenbergSourceExampleId = keyof typeof examples;

export function getSchoenbergSourceExample(
  id: SchoenbergSourceExampleId,
): SourceScoreExample {
  return examples[id];
}

export const schoenbergSourceExamples = examples;
